---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart mywebapp
  ansible.builtin.systemd:
    name: mywebapp.service
    state: restarted

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
